Update : separate tool into runGC and plot & delete zip inputs
workflow4metabolomics/metaMS pull request #29
Opened 2019-05-21 13:32 UTC by jsaintvanne

2019-05-29 14:26 UTC, lecorguille requested changes

2019-05-29 14:26 UTC, lecorguille commented on tools/metaMS_plot/.shed.yml
> +owner: jsaintvanne
Tu peux mettre workflow4metabolomics comme owner ?
C'est pas juste pour toi, nous aurions du faire ça depuis le début.

Si tu te sens lésé, pas de soucis. Garde jsaintvanne mais donne les droits à workflow4metabolomics.

2019-05-29 14:26 UTC, lecorguille commented on tools/metaMS_plot/README.rst
> +   Phone: +33 2 40 48 78 80
C'est pas un peu too much, le téléphone et l'adresse.
Je pense que l'email suffit ?

2019-05-29 14:26 UTC, lecorguille commented on tools/metaMS_plot/metaMS_plot.r
> +#!/usr/local/public/bin/Rscript --vanilla --slave --no-site-file
`#!/usr/bin/env Rscript --vanilla --slave --no-site-file`
Ca s'adapte plus au infra où Rscript peut être installer n'importe où (c'est encore plus vrai avec Conda)

2019-05-29 14:26 UTC, lecorguille commented on tools/metaMS_plot/metaMS_plot.r
> +load(args[["metaMS"]])
Tant qu'on en est à réécrire le code.
Est-ce que tu peux transformer ces
`args[["truc"]]` en `args$truc`

J'avais fait ça par méconnaissance. $ est plus lisible

2019-05-29 14:26 UTC, lecorguille commented on tools/metaMS_plot/metaMS_plot.xml
> +        <conditional name="selectedtic">
Pourquoi mettre un `conditional` si vous ne vous en servez pas ?

2019-05-29 14:26 UTC, lecorguille commented on tools/metaMS_plot/metaMS_plot.xml
> +        <conditional name="selectedbpc">
Pareil, pourquoi mettre un conditional si vous ne vous en servez pas ?

2019-05-29 14:26 UTC, lecorguille commented on tools/metaMS_plot/metaMS_plot.xml
> +TODO : Update the help section
Est-ce que c'est TODO sont encore d'actualité ?

2019-05-29 14:26 UTC, lecorguille commented on tools/metaMS_plot/metaMS_plot.xml
> +/!\\ WORK IN PROGRESS /!\\
WHAT?

2019-05-29 14:26 UTC, lecorguille commented on tools/metaMS_plot/metaMS_plot.xml
> +**Galaxy wrapper and scripts developpers** Guitton Yann LABERCA yann.guitton@oniris-nantes.fr
Ajoutes-toi

2019-05-29 14:26 UTC, lecorguille commented on tools/metaMS_plot/metaMS_plot.xml
> +        <data name="log" format="txt" from_work_dir="log.txt" label="plot_metaMS.log" />
Est-ce que ce fichier de log apporte vraiment quelque chose à l'utilisateur ?

2019-05-29 14:26 UTC, lecorguille commented on tools/metaMS_runGC/README.rst
> +GC-MS data processing version 2.1.1
C'est quoi ce numéro de version ?

2019-05-29 14:26 UTC, lecorguille commented on tools/metaMS_runGC/metaMS_runGC.r
> +if (args[["ri"]]!="NULL"){
Pareil, est-ce que tu peux réduire en `args$ri` ?

2019-05-29 14:26 UTC, lecorguille commented on tools/metaMS_runGC/metaMS_runGC.r
> +	fwhmparam=args[["fwhm"]]
Indentation

2019-05-29 14:26 UTC, lecorguille commented on tools/metaMS_runGC/metaMS_runGC.r
> +	GALAXY.GC <- metaMSsettings("protocolName" = "GALAXY.GC",
Indentation

2019-05-29 14:26 UTC, lecorguille commented on tools/macros/macros.xml
> +        <stdio>
Indentation

2019-05-29 14:26 UTC, lecorguille commented on tools/metaMS_plot/metaMS_plot.xml
> +    LC_ALL=C Rscript $__tool_directory__/metaMS_plot.r
Utilise ton token `@COMMAND_RSCRIPT@`

2019-05-29 14:26 UTC, lecorguille commented on tools/metaMS_plot/metaMS_plot.xml
> +        metaMS $metaMS
`metaMS '$metaMS'`
Il faut protéger les fichiers entre ''

2019-05-29 14:26 UTC, lecorguille commented on tools/metaMS_runGC/metams_runGC.xml
> +            <param name="settings|setting" value="gcdefault" />
Utilise les balises `<conditional name=` au lieu des formes `"settings|setting"`

2019-05-29 14:26 UTC, lecorguille commented on tools/metaMS_runGC/metams_runGC.xml
> +<!--TODO : Update the help section-->
Ce TODO est-il toujours utile ?

2019-05-29 14:28 UTC, jsaintvanne commented on tools/metaMS_plot/.shed.yml
> +owner: jsaintvanne
ha non j'ai zappé :p

2019-05-29 14:28 UTC, jsaintvanne commented on tools/metaMS_plot/README.rst
> +   Phone: +33 2 40 48 78 80
C'était mis comme ça mais je peux enlever ;)

2019-06-03 08:04 UTC, jsaintvanne reviewed
Pour les 2 conditional, c'est pour que l'utilisateur puisse choisir s'il veut le TIC ou non, pareil pour le BPC. Y-a-t-il un autre moyen de lui demander ?

Pour les "conflicting files" comment je résoud cela ? tu peux me donner les "write access" ? :)

2019-06-03 08:04 UTC, jsaintvanne commented on tools/metaMS_plot/metaMS_plot.xml
> +        <conditional name="selectedtic">
comment ça ?

2019-06-03 08:04 UTC, jsaintvanne commented on tools/metaMS_plot/metaMS_plot.xml
> +        <data name="log" format="txt" from_work_dir="log.txt" label="plot_metaMS.log" />
j'ai mis par défaut mais je peux enlever le fichier log facilement oui :)

2019-06-03 08:04 UTC, jsaintvanne commented on tools/metaMS_plot/metaMS_plot.xml
> +TODO : Update the help section
Yes ! les tests sur les EIC j'ai un soucis avec le ghostscript qui permet de merger les pdf... Ca passe en local car je l'ai installé mais j'arrive pas à le faire passer en ligne avec travis :/

2019-06-03 08:04 UTC, jsaintvanne commented on tools/metaMS_plot/metaMS_plot.xml
> +/!\\ WORK IN PROGRESS /!\\
oupsi ! pas update ce readme !

2019-06-03 08:04 UTC, jsaintvanne commented on tools/metaMS_runGC/README.rst
> +GC-MS data processing version 2.1.1
hum celui qui était là avant, je le remplace en 3.0.0 !

2019-06-03 08:04 UTC, jsaintvanne commented on tools/metaMS_plot/metaMS_plot.xml
> +        <conditional name="selectedtic">
Comment je pourrais ne pas tout le temps sortir le TIC si je n'en met pas ?
Ce conditionnal permet à l'utilisateur de demander de sortir le TIC ou non...

2019-06-03 08:04 UTC, jsaintvanne commented on tools/metaMS_plot/metaMS_plot.xml
> +        <conditional name="selectedbpc">
Ce conditionnal permet à l'utilisateur de demander de sortir le BPC ou non...

2019-06-03 09:20 UTC, lecorguille commented on tools/metaMS_plot/metaMS_plot.r
> +#!/usr/local/public/bin/Rscript --vanilla --slave --no-site-file
C'est moi, ou tu as juste virer le Shebang ?

2019-06-03 09:22 UTC, jsaintvanne commented on tools/metaMS_plot/metaMS_plot.r
> +#!/usr/local/public/bin/Rscript --vanilla --slave --no-site-file
ha c'était pas ça ? 
j'ai pa compris du coup ce que tu voulais dire :/

2019-06-03 09:24 UTC, lecorguille commented on tools/metaMS_plot/metaMS_plot.xml
> +        <conditional name="selectedtic">
Tu peux mettre un `type="boolean"` sans `<conditional>`. 
```
            <when value="true"/>
            <when value="false"/>
```
Montre que tu n'utilises pas vraiment de conditional. Les conditionals permettent de montrer ou non des options en fonction d'un choix de l'utilisateur.

Il te faudra adapter tes `<filter>` dans `<outputs>` par la même occasion

2019-06-03 09:24 UTC, lecorguille commented on tools/metaMS_plot/metaMS_plot.xml
> +        <conditional name="selectedbpc">
Pareil que plus haut.

2019-06-03 09:26 UTC, lecorguille commented on tools/metaMS_plot/metaMS_plot.xml
> +TODO : Update the help section
Cela veut dire que ton outil n'est pas portable en l'état.
Regarde de ce côté si ça n'est pas déjà fait : https://anaconda.org/conda-forge/ghostscript

2019-06-03 09:28 UTC, lecorguille commented on tools/metaMS_plot/metaMS_plot.xml
> +        <data name="log" format="txt" from_work_dir="log.txt" label="plot_metaMS.log" />
Supprime si il n'est pas utile.

2019-06-03 09:28 UTC, lecorguille commented on tools/metaMS_runGC/README.rst
> +GC-MS data processing version 2.1.1
Ou vire cette mention

2019-06-03 09:29 UTC, lecorguille commented on tools/metaMS_runGC/metaMS_runGC.r
> +if (args[["ri"]]!="NULL"){
Super !

2019-06-03 09:31 UTC, lecorguille commented on tools/metaMS_runGC/metaMS_runGC.r
> +	fwhmparam=args[["fwhm"]]
Si possible, remplace tous les tab par 4 espaces.
Il y a un mélange

2019-06-03 09:32 UTC, lecorguille commented on tools/metaMS_plot/metaMS_plot.xml
> +        metaMS $metaMS
Simple quote `'` par double `"`

2019-06-04 13:57 UTC, jsaintvanne commented
Plus de conflits, ça y est ! donc les tests sont dispos directement ici :)

Il reste le shebang que je n'ai pas tout à fais compris, ainsi que la partie plus importante du test sur les EICs avec `ghostscript` ! Pour l'instant, je l'ai ajouté dans les `requirements` mais la commande `gs` qui est utilisée n'est pas trouvable, d'où l'erreur dans les tests!

2019-06-12 11:45 UTC, lecorguille approved these changes

2019-06-12 11:45 UTC, merged